hbarton2/cscd350-f24-UnhandledExceptions

ClassItem.java
MethodItem.java

Added rename method function to ClassItem, added a getter and setter to MethodItem to properly update the method object in the map.

Added Rename method function to ClassItem.java

---

Main.java

changed renameClass to outprint instead of return.
lists classes before selecting class to rename/delete

Main rename fix

---

Main.java
UI.java

Included Help case and edited list of assistance needs, closed the scanner in the exit case as the program terminates

---

ClassItem.java

Added add/remove/change field methods to ClassItem.java, main features will still need to be added

Added field methods to ClassItem

---

Main.java
MethodItem.java
ParameterItem.java

Added types to ParameterItems, changed all methods that create an instance of a parameter item to input the type along with the parameter name.

Add type parameter

---

ClassItem.java
FieldItem.java
Main.java

Feature add type to fields

---

src/Main.java
src/UI.java
src/unittests.java

Added viewing relationship to listing class info. Changed UI method to return a string since it was only printing output anyways.

added viewing relationships in listing class info

---

src/ClassItem.java
src/UI.java
src/unittests.java

- Refactored unit tests for desired output.
- Removed .toLower() from field methods in classItem.java, couldn't find any issues with it but test yourself to verify.
- Added correct output to pass unit tests for listing class information.

Feature print fields

---

src/Main.java
src/UI.java

- Corrected syntax issue by flipping inputs in addField() call in main.
- Modified help accordingly.

corrected syntax issue for addfield

---

src/ClassItem.java
src/Main.java
src/UI.java

Added functionality for continuous prompting
Uses different menus to prompt the user so that we are able to "enter" a class and from there select what we want to do. Currently the only available options are add field and add method.
> fixed 'views' input handling to not cause error when invalid input is entered.
> added 'edit' switch case to provide functionality of above functionality. "edit className"

Feature continuous prompting new

---

src/RelationshipItem.java

Cleaned up code and deleted unnecessary code and comments.

added documentation and deleted unnecessary comments and code

---

uml/src/main/java/com/unhandledexceptions/Controller/BaseController.java
uml/src/main/java/com/unhandledexceptions/Model/ClassItem.java
uml/src/main/java/com/unhandledexceptions/Model/MethodItem.java
uml/src/main/java/com/unhandledexceptions/View/CLI.java
uml/src/main/java/com/unhandledexceptions/View/UI.java

I added types to methods, which seems to be the only thing we needed to add types to that I saw. This is only for the model and CLI, I didn't touch the GUI

109 user story specify data types for fields methods and parameters

---

README.md

Updated readme for maven instructions

103 task update readme potentially

---

uml/src/main/java/com/unhandledexceptions/Controller/BaseController.java
uml/src/main/java/com/unhandledexceptions/Model/ClassItem.java
uml/src/main/java/com/unhandledexceptions/View/ClassBox.java

added retypeField method to classItem.java as well as controller in BaseController. Then created methods and eventlisteners for for the field objects.

added rename/retype field functionality.

---

patterns.txt
uml/src/main/java/com/unhandledexceptions/Controller/BaseController.java
uml/src/main/java/com/unhandledexceptions/Controller/Caretaker.java
uml/src/main/java/com/unhandledexceptions/Controller/mainDiagramController.java
uml/src/main/java/com/unhandledexceptions/Model/ClassItem.java
uml/src/main/java/com/unhandledexceptions/Model/Data.java
uml/src/main/java/com/unhandledexceptions/Model/RelationshipItem.java
uml/src/main/java/com/unhandledexceptions/View/CLI.java
uml/src/main/java/com/unhandledexceptions/View/UI.java
uml/src/main/resources/fxml/mainDiagram.fxml
uml/src/test/java/ClassBoxTests.java
uml/src/test/java/MementoTests.java

Implemented undo and redo in both CLI and GUI using memento pattern.

152 memento design pattern

---

uml/src/main/java/com/unhandledexceptions/Controller/Caretaker.java
uml/src/main/java/com/unhandledexceptions/Controller/mainDiagramController.java
uml/src/main/java/com/unhandledexceptions/Model/Data.java
uml/src/main/java/com/unhandledexceptions/Model/MethodItem.java
uml/src/main/java/com/unhandledexceptions/Model/RelationshipItem.java
uml/src/main/java/com/unhandledexceptions/View/CLI.java
uml/src/main/java/com/unhandledexceptions/View/ClassBox.java
uml/src/test/java/ObserverTests.java

cli now saves relationship type in the case it needs to be not however the user types it. also, saving in cli auto appends .json if the user didn't.
sidequest: removed a few unused imports to clear up warnings.

fixed issue + small save file bugfix

---

uml/src/main/java/com/unhandledexceptions/Model/ClassItem.java

addClassItem Is now firing the InitialPostion method before returning "good" to ensure the created class box is not only at coordinate 0/0

initialPosition method fires inside addClassItem

---

uml/src/main/java/com/unhandledexceptions/Controller/mainDiagramController.java
uml/src/main/java/com/unhandledexceptions/View/ClassBox.java
uml/src/main/java/com/unhandledexceptions/View/RelationLine.java

- getX and getY for dragging set name to lowercase before searching
- getting classItem searches only for lowercase name
- relationLine names are now set to lowercase before searching

Fixed Bugs with Uppercase class names

---

uml/src/main/java/com/unhandledexceptions/Model/ClassItem.java
uml/src/main/java/com/unhandledexceptions/View/ClassBox.java
uml/src/test/java/ClassBoxTests.java

fixed some return strings in ClassItem, for removing field.
added functionality to delete a field
> select the field in the list, and hit 'Delete' key.
> opens confirmation window to confirm action

180 user story delete fields from a class

---

uml/src/main/java/com/unhandledexceptions/Controller/mainDiagramController.java
uml/src/main/resources/fxml/mainDiagram.fxml

Replaced "about" in our help menu with "keyboard shortcuts". Clicking keyboard shortcuts creates a popup or information alert displaying our shortcuts. If I missed any feel free to let me know and I can change it.

185 task finish help menu in gui

---

uml/src/main/java/com/unhandledexceptions/Controller/mainDiagramController.java
uml/src/main/java/com/unhandledexceptions/View/ClassBox.java

Added functionality to delete a method using the delete key. Added input handling for if the user leaves a type or a name blank for adding a method or parameter.

191 bug methods and parameter blank input error handling

---

uml/src/main/java/com/unhandledexceptions/Model/Data.java
uml/src/main/java/com/unhandledexceptions/View/UI.java

Added error handling for loading so program doesn't crash. Also updated screenshot when menu option in CLI to display syntax.

186 bug load command in cli does no error checking

---

uml/src/main/java/com/unhandledexceptions/Model/ClassItem.java

with zooming in and out working, the GUI can now make as many class boxes as you would like

Hardcap for random positioning for classboxes is gone
